---
apiVersion: v1
kind: Namespace
metadata:
  name: client1-namespace

---
# DockerHub secret (run separately, not part of YAML)
# kubectl create secret docker-registry dockerhub-secret \
#   --docker-username=YOUR_USERNAME \
#   --docker-password=YOUR_PASSWORD \
#   --docker-email=YOUR_EMAIL \
#   -n client1-namespace

---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client1
  namespace: client1-namespace
  labels:
    app: mongo-client1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client1
  template:
    metadata:
      labels:
        app: mongo-client1
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}

---
# MongoDB Service (headless for direct connection)
apiVersion: v1
kind: Service
metadata:
  name: mongo-client1
  namespace: client1-namespace
spec:
  selector:
    app: mongo-client1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None

---
# Backend Deployment (Express)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1-backend-deployment
  namespace: client1-namespace
  labels:
    app: client1-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1-backend
  template:
    metadata:
      labels:
        app: client1-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: backend
          image: kanagaraj1998/kube-jenkins:client1-backend-v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-client1:27017/mydb
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 30
          #   periodSeconds: 20

---
# Backend Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: client1-backend-service
  namespace: client1-namespace
spec:
  selector:
    app: client1-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
# Frontend Deployment (React)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1-frontend-deployment
  namespace: client1-namespace
  labels:
    app: client1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1-frontend
  template:
    metadata:
      labels:
        app: client1-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: frontend
          image: kanagaraj1998/kube-jenkins:client1-frontend-v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 20
          #   periodSeconds: 20

---
# Frontend Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: client1-frontend-service
  namespace: client1-namespace
spec:
  selector:
    app: client1-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
