---
apiVersion: v1
kind: Namespace
metadata:
  name: client1-namespace

---
# 🗄️ Backend Deployment (Express)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1-backend-deployment
  namespace: client1-namespace
  labels:
    app: client1-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client1-backend
  template:
    metadata:
      labels:
        app: client1-backend
    spec:
      containers:
        - name: backend
          image: kanagaraj1998/kube-jenkins:client1-backend-latest   # replaced dynamically in Jenkins
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-client1:27017/mydb
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: client1-backend-service
  namespace: client1-namespace
spec:
  selector:
    app: client1-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
# 💻 Frontend Deployment (React)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1-frontend-deployment
  namespace: client1-namespace
  labels:
    app: client1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1-frontend
  template:
    metadata:
      labels:
        app: client1-frontend
    spec:
      containers:
        - name: frontend
          image: kanagaraj1998/kube-jenkins:client1-frontend-latest   # replaced dynamically in Jenkins
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
